extends@: default

form:
    fields:
        tabs:
            fields:
                content:
                    fields:
                        header.products:
                            type: pages
                            multiple: true
                            label: Product choices
                            validate:
                                type: commalist
